### ISSUE TITLE
[R82XX] PLL not locked!

### ISSUE THREAD

**Issue by attie** [librtlsdr/librtlsdr#57] opened 2017-10-22 21:27 UTC
I've just tracked down an issue related to the PLL failing to lock, and thus decoding corrupt data.
It was failing on my new system (I build librtlsdr from source), and working fine on my old system (Ubuntu 14.04, using the `librtlsdr0` package, Version: 0.5.2.7.3ab6-1).

A quick bisect has shown up d892279085491f9c610388da89bc701ef6ac632c as the first bad commit.

I'm somewhat suprised by this, given the commit's age (~2 years 7 months), but reverting to its parent (d447a2e) has solved the problem for me.

I will look into this further when I can, but for now will be using d447a2e and confirming that it provides good data.

I'm running Ubuntu 16.04.3 on an i7-7700K.

**Comment by attie** [comment] 2017-10-22 21:42
Package info from functional Ubuntu 14.04 on i7-2600

```
$ apt-cache show librtlsdr0
Package: librtlsdr0
Priority: extra
Section: universe/libs
Installed-Size: 114
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Adam Cécile (Le_Vert) <gandalf@le-vert.net>
Architecture: amd64
Source: rtl-sdr
Version: 0.5.2.7.3ab6-1
Depends: libc6 (>= 2.14), libusb-1.0-0 (>= 2:1.0.8)
Pre-Depends: multiarch-support
Filename: pool/universe/r/rtl-sdr/librtlsdr0_0.5.2.7.3ab6-1_amd64.deb
Size: 26488
MD5sum: 928419846cc69885ff51fbda362a36b5
SHA1: 9605b19c22ed1d28d6de8d6a1f39281df2039253
SHA256: 01574a47a9867a37c2a8ff11fff65ba9920ab0e6ae76f5da754144a86d130c94
Description-en: Software defined radio receiver for Realtek RTL2832U (development files)
 rtl-sdr is a software defined radio (SDR) receiver software for certain
 low-cost DVB-T/DAB(+) USB dongles based on the Realtek RTL2832U chip.
 .
 This package contains development files.
Description-md5: 83ca0f034542873ebb35fc804478ed50
Multi-Arch: same
Homepage: http://sdr.osmocom.org/trac/wiki/rtl-sdr
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
```

**Comment by attie** [comment] 2017-10-22 21:45
Problems on Ubuntu 16.04 on i7-7700K (built from c7d970a)
```
$ ./rtl_test
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
[R82XX] PLL not locked!
Sampling at 2048000 S/s.

Info: This tool will continuously read from the device, and report if
samples get lost. If you observe no further output, everything is fine.

Reading samples in async mode...
```

Less(?) problems on Ubuntu 16.04 on i7-7700K (built from d447a2e)
```
$ ./rtl_test
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6
Sampling at 2048000 S/s.

Info: This tool will continuously read from the device, and report if
samples get lost. If you observe no further output, everything is fine.

Reading samples in async mode...
```

**Comment by attie** [comment] 2017-10-25 14:37
Further investigation shows that the `[R82XX] PLL not locked!` does in fact not appear to be a problem.
Actually, moving the antenna a couple of meters allowed me to receive a signal from a neighbour as well as mine...

I have had my application running on the i7-7700k with c7d970a for the past few days, and the data points coming from two(!) devices are stable.

I don't think closing the issue is appropriate yet, as running on the i7-2600 with c7d970a also shows the `[R82XX] PLL not locked!` message.

* Can this message be safely ignored?
* How come it's started showing up since d892279?
* What can we do to fix the issue?

**Comment by wgaylord** [comment] 2018-01-06 00:55
I found the cause of this to actually have to do with the calling order of some functions. (A Python library using librtlsdr found this.)
https://github.com/roger-/pyrtlsdr/issues/72 Shows that the calling order generates this. Not sure if its easily fixable here.

**Comment by wgaylord** [comment] 2018-02-06 19:59
I have a reason why it began happening. I believe it is because the bandwidth is being set before the if freq. Which causes the chip to think you are doing stuff before the PLL has stetted and locked to the freq.

Shouldn't be an issue but I can make a PR to fix this. (Simple changing the order of calls in the r820t_set_bw function.) 

Now this could be not 100% correct but its from experimenting.

**Comment by attie** [comment] 2018-02-06 20:11
Interesting, thanks for the update.

I have been using things now since my last post with the "_error_" and without issues.

**Comment by hayguen** [comment] 2020-08-01 17:45
i am ignoring this warning ever since ..
is there a pull request for latest development branch?
can we simply close this issue?

**Comment by ValZapod** [comment] 2020-08-17 07:49
Yep I also got such warnings.))

**Comment by ValZapod** [comment] 2020-08-17 10:09
You should apply this patch https://github.com/librtlsdr/librtlsdr/commit/c28886f89b24e4cc73541710b2d6e6c013ed90c5 to check what are the freq. as BTW recommended here and is done in tuner_e4k.c and shown here https://inst.eecs.berkeley.edu/~ee123/fa13/rtl_sdr_install.html, I am also almost sure that it is just a low freq. that is not supported, not because of r820t_set_bw function. LOL.

**Comment by hayguen** [comment] 2020-08-18 09:41
ok, that patch https://github.com/librtlsdr/librtlsdr/commit/c28886f89b24e4cc73541710b2d6e6c013ed90c5 is already in the development branch

**Comment by ValZapod** [comment] 2020-08-18 09:46
> already in the development branch

But it is not in bisected tree before the breaking  commit d892279085491f9c610388da89bc701ef6ac632c (that is why I am "almost sure").

**Comment by ValZapod** [comment] 2020-08-18 12:00
Both kal -s GSM900 and rtl_test -p do not print that warning before https://github.com/librtlsdr/librtlsdr/commit/d892279085491f9c610388da89bc701ef6ac632c (as obviously both rtl_test and kal cannot set bandwidth before that, for 828D or 820T). 

NOW WHEN YOU checkout https://github.com/librtlsdr/librtlsdr/commit/d892279085491f9c610388da89bc701ef6ac632c and apply https://github.com/librtlsdr/librtlsdr/commit/c28886f89b24e4cc73541710b2d6e6c013ed90c5 on top it prints 

```
root@kali:~/# kal -s GSM900 -e 29 //-e is error in ppm
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner
Exact sample rate is: 270833.002142 Hz
[R82XX] PLL not locked for 2125000 Hz!
kal: Scanning for GSM-900 base stations.
GSM-900:
	chan: 25 (940.0MHz + 1.730kHz)	power: 179537.60
	chan: 43 (943.6MHz - 1.831kHz)	power: 177609.95
```

So it is not a bug in the code. 2.125 000 MHz is not supported. LOL! And then **I just add else with "PLL locked"** 
```
diff --git a/src/tuner_r82xx.c b/src/tuner_r82xx.c
index 0f84a0d..36ed3c9 100644
--- a/src/tuner_r82xx.c
+++ b/src/tuner_r82xx.c
@@ -550,7 +550,7 @@ static int r82xx_set_pll(struct r82xx_priv *priv, uint32_t freq)
                fprintf(stderr, "[R82XX] PLL not locked for %u Hz!\n", freq);
                priv->has_lock = 0;
                return 0;
-       }
+       } else fprintf(stderr, "[R82XX] PLL locked for %u Hz!\n", freq); //dumb, it is not stderr, but whatever
 
        priv->has_lock = 1;

```

and got

```
root@kali:/opt/SourceCode/librtlsdrnew# kal -s GSM900
Found 1 device(s):
  0:  Astrometa DVB-T/DVB-T2

Using device 0: Astrometa DVB-T/DVB-T2
Found Rafael Micro R828D tuner
[R82XX] PLL locked for 56000000 Hz! //supported
Exact sample rate is: 270833.002142 Hz
[R82XX] PLL not locked for 2125000 Hz! //not supported
kal: Scanning for GSM-900 base stations.
[R82XX] PLL locked for 937325000 Hz!
[R82XX] PLL locked for 937525000 Hz!
[R82XX] PLL locked for 937725000 Hz!
[R82XX] PLL locked for 937925000 Hz!
[R82XX] PLL locked for 938125000 Hz!
[R82XX] PLL locked for 938325000 Hz!
[R82XX] PLL locked for 938525000 Hz!
[R82XX] PLL locked for 938725000 Hz!
[R82XX] PLL locked for 938925000 Hz!
[R82XX] PLL locked for 939125000 Hz!
[R82XX] PLL locked for 939325000 Hz!
```

**Comment by hayguen** [comment] 2020-08-18 23:07
hope, latest patch on the development branch should fix this:
* looks, calling r82xx_set_pll() at initialization before having called r82xx_set_freq() produced the erroneous warning
* now just remembering last rf_freq given at r82xx_set_freq() to suppress the warning

tested with kal and rtl_fm: both look good

**Comment by ValZapod** [comment] 2020-08-18 23:33
But priv->has_lock = 0;
still has no lock, it cannot lock on such a low freq?? See my previous message.

Also did not it introuduce dead code??? With if ( priv->rf_freq )

Also you have tabs issues the first comment))

**Comment by hayguen** [comment] 2020-08-19 00:37
2nd try:
* at initialization from r82xx_set_tv_standard() the frequency wasn't set from outside. fixed this.
* suppression removed
* yes, for low frequencies (below 24 MHz for R820T), the PLL can't lock
* setting bandwidth - before having set frequency - provoked above error. now keeping previous frequency in r82xx_set_pll() when called to set 0.

**Comment by ValZapod** [comment] 2020-08-19 00:49
>  now keeping previous frequency in r82xx_set_pll() when called to set 0.

So it is this after all:
> Simple changing the order of calls in the r820t_set_bw function

**Comment by hayguen** [comment] 2020-08-19 00:51
No, changing the call order is not always the solution.
depending on the rtl tool, bandwidth is set before setting the frequency ..

**Comment by ValZapod** [comment] 2020-08-19 01:17
Okay, last question, why with kal it is:
[R82XX] PLL not locked at Tuner LO **1925000** Hz!

and with rtl_test -p it is 
[R82XX] PLL not locked at Tuner LO **1530000** Hz!

(is it because of **uninitialized variable** that is sending garbage, really)? Otherwise looks good to me, please pull https://github.com/steve-m/librtlsdr/commit/be1d1206bfb6e6c41f7d91b20b77e20f929fa6a7 as it is a memory leak.

**Comment by hayguen** [comment] 2020-08-19 01:27
> (is it because of uninitialized variable that is sending garbage, really)?

Don't think so: internal tuner frequency depends on bandwidth and automatic bandwidth depends on Samplerate. The different applications probably use different Samplerates ..
Will check that again .. tomorrow.

Memory leak: thanks for reminder.

**Comment by hayguen** [comment] 2020-08-19 08:59
kal does use 270833 Hz samplerate.

when calling rtl_test with same samplerate:
```
$ ./rtl_test -s 270833 -p
..
[R82XX] PLL locked at Tuner LO 56000000 Hz for RF 56000000 Hz!
..
r82xx_set_freq(freq = 56000000) @ LSB--> intfreq 1925000, ifcenter 0 --> f 57925000
[R82XX] PLL locked at Tuner LO 57925000 Hz for RF 56000000 Hz!
```
you can see intfreq of 1925 kHz - same as your not locked Tuner LO with kal.
thus, we don't have an uninitialized variable.

**Comment by hayguen** [comment] 2020-08-19 09:22
> please pull steve-m@be1d120 as it is a memory leak.

cherry-picked that patch

**Comment by ValZapod** [comment] 2020-08-19 16:04
Ok, if you are sure PLL lock in place where PLL lock was absent will not cause any problems, it is LGTM.

**Comment by hayguen** [comment] 2020-08-21 20:46
> I think there is a point to include this keenerd/rtl-sdr@c5d7ebe or even this keenerd/rtl-sdr@a710e4e to actually test this PLL thing...

yes, there definitely was a point to do so. found one more bug, see https://github.com/librtlsdr/librtlsdr/commit/e315a41ec5814523caaa3d4ac8f4fb775f1e96e6
and could clean the PLL warning messages.

note: ```rtl_test``` should be run twice for R820T/2 tuner:
once for (default) Lower  sideband and once again for Upper sideband:
```
$ ./rtl_test -O sb=L -t
..
Testing tuner range. This may take a couple of minutes..
Found a new band starting at 11921884 Hz
Tuning band: 11921884 - 1768469452 Hz

Found a new band starting at 1855120574 Hz
Tuning band: 1855120574 - 1870469938 Hz

Found a new band starting at 1970320645 Hz
Tuning band: 1970320645 - 1985669948 Hz

Found a new band starting at 2085520472 Hz
Tuning band: 2085520472 - 2100869958 Hz
```
still running for an rtl-sdr.com V3 .. yes, it takes several minutes!

aborted that and started for Upper sideband:
```
$ ./rtl_test -O sb=U -t
...
Testing tuner range. This may take a couple of minutes..
Found a new band starting at 14979620 Hz
Tuning band: 14979620 - 1771529461 Hz

Found a new band starting at 1858179057 Hz
Tuning band: 1858179057 - 1873529947 Hz

Found a new band starting at 1973379006 Hz
Tuning band: 1973379006 - 1988729957 Hz

Found a new band starting at 2088579077 Hz
Tuning band: 2088579077 - 2103929967 Hz
```

you can see, how the sideband selection effectively shifts the tuning range.

and the specs write, the tuning range would start around 24 MHz - or some lower ..
with this dongle already starting at ~ 12 MHz :-)

**Comment by hayguen** [comment] 2020-08-21 21:07
trying to test same with a NooElec NESDR Smart floods my terminal with errors and breaks:
```
r82xx_write_arr: i2c wr failed=-4 reg=17 len=1
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
r82xx_write_arr: i2c wr failed=-4 reg=06 len=1
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
rtlsdr_write_reg failed with -4

real	1m34.540s
user	0m0.397s
sys	0m1.231s
```
even with 2nd and 3rd try, i could not get a full run :-(

**Comment by hayguen** [comment] 2020-08-21 21:12
> This is a known bug.

with a solution?
strange anyway, that it runs fine with V3 dongle ..

**Comment by hayguen** [comment] 2020-08-21 22:20
that code look really strange: why is there a call to rtlsdr_i2c_write_fn() inside a r82xx_read() function.
as you say, in the development branch, the rtlsdr_i2c_write_fn() was removed ..

no idea what you mean: which i2c patch to revert .. at which fork?

looking around, i see
```
	/** No such device (it may have been disconnected) */
	LIBUSB_ERROR_NO_DEVICE = -4,
```
in libusb.h .. besides that, dongles get quite hot. but i'm not sure if this might cause this!?

the effective call to libusb is
```
libusb_control_transfer(dev->devh, CTRL_OUT, 0, addr, index, array, len, CTRL_TIMEOUT);
```
with `CTRL_TIMEOUT` of 300 ms.
Retried with 500 ms .. produced a quicker Fail! But the dongle was really hot, cause still quite warm at start.
Having it cooled down - disconnected from USB - and retrying produced a FAIL after 1m43.606 secs.
Direct retry again: FAIL after 0.747 secs.

IMHO, that looks like a temperature problem  - depending on the Dongle!

**Comment by hayguen** [comment] 2020-08-21 22:40
sure?! can you track this to the commit breaking it with git bisect?
i put my NooElec dongle into the fridge - after it nearly burnt my fingers ..
and have some mods in rtl_test .. waiting some seconds after error -4 == LIBUSB_ERROR_NO_DEVICE ..

**Comment by hayguen** [comment] 2020-08-21 23:09
now getting early abort - before flooding the terminal, with https://github.com/librtlsdr/librtlsdr/commit/04ce5ec246460d3a864daf9a36d4578d189bacf0

but even with the cooled down NooElec dongle:
```
$ time ./rtl_test -O sb=L -t
...
Testing tuner range. This may take a couple of minutes..
Found a new band starting at 11869965 Hz
r82xx_write_arr: i2c wr failed=-4 reg=1a len=1
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
FIND_END: Got Error -4 for frequency 924819212 .. retry after wait ..
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
r82xx_write_arr: i2c wr failed=-4 reg=17 len=1
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
FIND_END: Got Error -4 .. again. Giving Up!
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
r82xx_write_arr: i2c wr failed=-4 reg=06 len=1
rtlsdr_demod_write_reg failed with -4
rtlsdr_demod_read_reg failed with -4
rtlsdr_write_reg failed with -4

real	1m44.345s
user	0m0.624s
sys	0m0.972s
```
while the V3 has no problems.

**Comment by hayguen** [comment] 2020-08-22 23:16
> is the same as keenerd/rtl-sdr@0bba67a?

at least same place/return

> And I could have told you that it is not temp. problem.

sure? how? the reason is still open!
now trying with another Dongle: Green 'NEWGEN':
```
$ src/rtl_test -t
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T/2 tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 
Sampling at 2048000 S/s.
Testing tuner range. This may take a couple of minutes..
Found a new band starting at 11880620 Hz
Tuning band: 11880620 - 1768469499 Hz

Found a new band starting at 1855068802 Hz
Tuning band: 1855068802 - 1870469985 Hz

Found a new band starting at 1970268629 Hz
Tuning band: 1970268629 - 1985669995 Hz

Found a new band starting at 2085468334 Hz
Tuning band: 2085468334 - 2100869944 Hz

^C
Signal caught, exiting!

$ time src/rtl_test -t -O sb=U
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T/2 tuner
Supported gain values (29): 0.0 0.9 1.4 2.7 3.7 7.7 8.7 12.5 14.4 15.7 16.6 19.7 20.7 22.9 25.4 28.0 29.7 32.8 33.8 36.4 37.2 38.6 40.2 42.1 43.4 43.9 44.5 48.0 49.6 
Sampling at 2048000 S/s.

rtlsdr_set_opt_string(): parsed sideband 1 == Upper
  application of parsed option returned 0
Testing tuner range. This may take a couple of minutes..
Found a new band starting at 14926159 Hz
Tuning band: 14926159 - 1771529486 Hz

Found a new band starting at 1858120671 Hz
Tuning band: 1858120671 - 1873529972 Hz

Found a new band starting at 1973320803 Hz
Tuning band: 1973320803 - 1988729982 Hz

Found a new band starting at 2088520691 Hz
Tuning band: 2088520691 - 2103929992 Hz

^C
Signal caught, exiting!

real	3m27.275s
user	0m0.890s
sys	0m2.098s
```
runs fine :-)

now, wanted to test with a Noxon Dongle with E4000 tuner: Oh my! lots of error messages:
```
[E4K] PLL not locked for 10000 Hz!
[E4K] PLL not locked for 20000 Hz!
[E4K] PLL not locked for 30000 Hz!
```

**Comment by hayguen** [comment] 2020-08-22 23:21
yes, i know. but there should not be that many output with `rtl_test -t`.
i'll remove that printfs ..

**Closed as completed** 2020-09-03 19:52 UTC
Labels: verify
